package by.it.narushevich.jd03_01;

import java.sql.SQLException;
import java.sql.Statement;

public class A_AddData {

    public static void createCollection(Statement statement) throws SQLException {

        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','English Tea #1','cardboard','28 x 32','2017.04.01', '02-08-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Cinnamon Haze','cardboard','28 x 32','2018.05.05','02-08-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Earl Grey','cardboard','28 x 32','2002.01.07','02-09-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Earl Grey','cardboard','28 x 32','2005.09.14','02-09-2',1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Green Tea','cardboard','28 x 32','2008.04.18','02-09-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','English Breakfast','cardboard','28 x 32','2001.04.05','02-10-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','English Breakfast','cardboard','28 x 32','1998.10.18','02-10-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Lemon & Lime Twist','cardboard','28 x 32','2018.01.06','02-10-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'AHMAD TEA','Classic black tea','cardboard','28 x 32','2013.05.20','02-10-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','Yellow Label tea','cardboard','28 x 32','2012.03.20','02-11-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','Yellow Label tea', 'cardboard', '28 x 32', '2005.03.20','02-11-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','Royal Ceylon', 'cardboard', '28 x 32', '2003.05.10','02-11-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','A moment to energise', 'cardboard', '26 x 28', '2017.12.31','02-13-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','A moment to balance', 'cardboard', '26 x 28', '2017.12.31','02-13-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','pure black ceylon', 'paper', '22 x 22', '2007.02.15','01-17-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','cherry morello', 'paper', '22 x 22', '2007.10.12','01-17-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','pear chocolate', 'paper', '22 x 22', '2007.08.29','01-17-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','flirty lady', 'paper', '20 x 20', '2015.07.14','01-17-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','blue fruit', 'paper', '22 x 22', '2011.03.20','01-17-5', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton','Orange Jaipur', 'paper', '22 x 22', '2006.12.16','01-18-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Jaf tea', 'temptation', 'cardboard', '23 x 28', '2001.10.02','01-14-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Greenfield', 'finelly selected speciality tea', 'paper', '20 x 28', '2003.05.16','01-15-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Princess Java', 'black', 'paper', '20 x 28', '2000.12.28','01-06-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Natursan', 'La via del te firenze', 'paper', '20 x 28', '2005.09.12','01-04-5', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Mistral', 'Cristmas tea', 'cardboard', '23 x 28', '2017.12.25','01-27-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Chelton', '100% pure ceylon tea', 'cardboard','28 x 32', '2003.11.12','02-04-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Auchan', 'Black tea', 'cardboard', '28 x 32', '2018.04.06','02-01-1', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lipton', 'Russian Earl Grey', 'cardboard', '25 x 30', '2010.05.20','02-12-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Akbar', 'English breakfast', 'cardboard', '28 x 32', '2007.08.31','02-19-4', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Akbar', 'flavoured tea', 'cardboard', '28 x 32', '2011.05.10','02-19-3', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Lord Nelson', 'Lemon & Ginger', 'cardboard', '28 x 32', '2015.10.18','02-21-2', 1);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Forest of Arden', '2006', 'paper', '20 x 28', '2008.09.15','01-02-4', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Mabroc', '1001 night', 'paper', '20 x 28', '2010.04.20','01-02-2', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Maitre de The', 'Noir', 'paper', '23 x 28', '2002.01.19','01-04-2', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Messmer', 'Zitrone', 'cardboard', '28 x 32', '2009.02.14','02-26-1', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Kakoo', 'Green tea bags', 'paper', '25 x 28', '2010.11.05','02-26-2', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Tea', 'green', 'paper', '20 x 20', '2010.11.06','01-03-3', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Dilmah', 'Ceylon gold', 'paper', '25 x 30', '2010.04.09','02-06-3', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Dilmah', 'Lychee', 'paper', '20 x 28', '2012.03.22','01-09-4', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Dilmah', 'Earl Grey', 'paper', '20 x 28', '2012.01.19','01-09-5', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Dilmah', 'Strawberry tea', 'paper', '20 x 28', '2012.06.15','01-09-2', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Dilmah', 'Natural green tea', 'paper', '20 x 28', '2012.07.25','01-09-1', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Pickwick', 'finest taste', 'paper', '25 x 30', '2006.07.14','01-16-1', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Malwa', 'Exclusive smak natury', 'paper', '20 x 28', '2016.12.15','01-24-3', 2);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Brooke Bond', 'history', 'cardboard', '28 x 32', '2008.04.14','02-35-1', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Brooke Bond', 'history', 'cardboard', '28 x 32', '2008.04.14','02-35-2', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Brooke Bond', 'history', 'cardboard', '28 x 32', '2008.04.14','02-35-3', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Golden bowl', 'strawberry', 'paper', '25 x 28', '2011.06.30','02-39-3', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Golden bowl', 'green tea', 'cardboard', '26 x 28', '2010.03.25','02-38-4', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Golden bowl', 'black tea', 'cardboard', '28 x 32', '2007.12.15','02-38-3', 3);");
        statement.executeUpdate("INSERT INTO narushevich_ab.teatags (`id`, `trademark`, `subtitle`, `material`, `width_x_height`, `in_collection_since`, `num_in_catalog`, `fk_users`) VALUES (DEFAULT,'Golden bowl', 'indian', 'cardboard', '26 x 28', '2010.05.04','02-38-1', 3);");
    }
}
