//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.14 at 12:15:44 PM MSK 
//


package by.it.eslaikouskaya.jd02_09.beans;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catalogs" type="{http://beans.jd02_09.eslaikouskaya.it.by/}Catalogs"/>
 *         &lt;element name="aboutus" type="{http://beans.jd02_09.eslaikouskaya.it.by/}AboutUs"/>
 *         &lt;element name="shortinfo" type="{http://beans.jd02_09.eslaikouskaya.it.by/}ShortInfo"/>
 *         &lt;element name="properties" type="{http://beans.jd02_09.eslaikouskaya.it.by/}Properties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"catalogs",
		"aboutus",
		"shortinfo",
		"properties"
})
@XmlRootElement(name = "cite")
public class Cite {

	@XmlElement(required = true)
	protected Catalogs catalogs;
	@XmlElement(required = true)
	protected AboutUs aboutus;
	@XmlElement(required = true)
	protected ShortInfo shortinfo;
	@XmlElement(required = true)
	protected Properties properties;

	/**
	 * Gets the value of the catalogs property.
	 *
	 * @return possible object is
	 * {@link Catalogs }
	 */
	public Catalogs getCatalogs() {
		return catalogs;
	}

	/**
	 * Sets the value of the catalogs property.
	 *
	 * @param value allowed object is
	 *              {@link Catalogs }
	 */
	public void setCatalogs(Catalogs value) {
		this.catalogs = value;
	}

	/**
	 * Gets the value of the aboutus property.
	 *
	 * @return possible object is
	 * {@link AboutUs }
	 */
	public AboutUs getAboutus() {
		return aboutus;
	}

	/**
	 * Sets the value of the aboutus property.
	 *
	 * @param value allowed object is
	 *              {@link AboutUs }
	 */
	public void setAboutus(AboutUs value) {
		this.aboutus = value;
	}

	/**
	 * Gets the value of the shortinfo property.
	 *
	 * @return possible object is
	 * {@link ShortInfo }
	 */
	public ShortInfo getShortinfo() {
		return shortinfo;
	}

	/**
	 * Sets the value of the shortinfo property.
	 *
	 * @param value allowed object is
	 *              {@link ShortInfo }
	 */
	public void setShortinfo(ShortInfo value) {
		this.shortinfo = value;
	}

	/**
	 * Gets the value of the properties property.
	 *
	 * @return possible object is
	 * {@link Properties }
	 */
	public Properties getProperties() {
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 *
	 * @param value allowed object is
	 *              {@link Properties }
	 */
	public void setProperties(Properties value) {
		this.properties = value;
	}

}
