//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.14 at 12:15:44 PM MSK 
//


package by.it.eslaikouskaya.jd02_09.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the by.it.eslaikouskaya.jd02_09.beans package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.eslaikouskaya.jd02_09.beans
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Cite }
	 */
	public Cite createCite() {
		return new Cite();
	}

	/**
	 * Create an instance of {@link Catalogs }
	 */
	public Catalogs createCatalogs() {
		return new Catalogs();
	}

	/**
	 * Create an instance of {@link AboutUs }
	 */
	public AboutUs createAboutUs() {
		return new AboutUs();
	}

	/**
	 * Create an instance of {@link ShortInfo }
	 */
	public ShortInfo createShortInfo() {
		return new ShortInfo();
	}

	/**
	 * Create an instance of {@link Properties }
	 */
	public Properties createProperties() {
		return new Properties();
	}

	/**
	 * Create an instance of {@link Element }
	 */
	public Element createElement() {
		return new Element();
	}

	/**
	 * Create an instance of {@link Elements }
	 */
	public Elements createElements() {
		return new Elements();
	}

	/**
	 * Create an instance of {@link Property }
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link Catalog }
	 */
	public Catalog createCatalog() {
		return new Catalog();
	}

}
