//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.14 at 12:15:44 PM MSK 
//


package by.it.eslaikouskaya.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShortInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ShortInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managerstel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShortInfo", propOrder = {
		"city",
		"address",
		"notation",
		"managerstel"
})
public class ShortInfo {

	@XmlElement(required = true)
	protected String city;
	@XmlElement(required = true)
	protected String address;
	@XmlElement(required = true)
	protected String notation;
	@XmlElement(required = true)
	protected String managerstel;

	/**
	 * Gets the value of the city property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the address property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAddress(String value) {
		this.address = value;
	}

	/**
	 * Gets the value of the notation property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getNotation() {
		return notation;
	}

	/**
	 * Sets the value of the notation property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setNotation(String value) {
		this.notation = value;
	}

	/**
	 * Gets the value of the managerstel property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getManagerstel() {
		return managerstel;
	}

	/**
	 * Sets the value of the managerstel property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setManagerstel(String value) {
		this.managerstel = value;
	}

}
